"""empty message

Revision ID: 81f6122727ff
Revises: 8cf7f5a92553
Create Date: 2026-01-23 18:41:51.402194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f6122727ff'
down_revision = '8cf7f5a92553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_enti_donatori')
    op.drop_table('beni')
    op.drop_table('segnalazioni')
    op.drop_table('donazioni_monetarie')
    op.drop_table('prenotazioni')
    op.drop_table('punti_distribuzione')
    op.drop_table('macro_categorie')
    op.drop_table('sotto_categorie')
    op.drop_table('accounts')
    op.drop_table('account_enti_erogatori')
    op.drop_table('account_beneficiari')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_beneficiari',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cognome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_table('account_enti_erogatori',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipologia_ente', sa.VARCHAR(length=100), nullable=False),
    sa.Column('iban', sa.VARCHAR(length=34), nullable=True),
    sa.Column('indirizzo_sede', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sotto_categorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_categorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('punti_distribuzione',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('indirizzo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('latitudine', sa.FLOAT(), nullable=False),
    sa.Column('longitudine', sa.FLOAT(), nullable=False),
    sa.Column('orari', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ente_erogatore_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ente_erogatore_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prenotazioni',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beneficiario_id', sa.INTEGER(), nullable=False),
    sa.Column('bene_id', sa.INTEGER(), nullable=False),
    sa.Column('data_prenotazione', sa.DATETIME(), nullable=False),
    sa.Column('stato', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codice_qr', sa.VARCHAR(length=36), nullable=False),
    sa.Column('punto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bene_id'], ['beni.id'], ),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['account_beneficiari.id'], ),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_qr')
    )
    op.create_table('donazioni_monetarie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donatore_id', sa.INTEGER(), nullable=False),
    sa.Column('ente_id', sa.INTEGER(), nullable=False),
    sa.Column('importo', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['donatore_id'], ['account_enti_donatori.id'], ),
    sa.ForeignKeyConstraint(['ente_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segnalazioni',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('latitudine', sa.FLOAT(), nullable=False),
    sa.Column('longitudine', sa.FLOAT(), nullable=False),
    sa.Column('tipo_bisogno', sa.VARCHAR(length=19), nullable=True),
    sa.Column('stato_approvazione', sa.VARCHAR(length=9), nullable=False),
    sa.Column('punto_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('utente_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('quantita', sa.INTEGER(), nullable=False),
    sa.Column('punto_distribuzione_id', sa.INTEGER(), nullable=False),
    sa.Column('sottocategoria_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['punto_distribuzione_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sotto_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_enti_donatori',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('partita_iva', sa.VARCHAR(length=11), nullable=False),
    sa.Column('nome_attivita', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    # ### end Alembic commands ###
