"""creazione

Revision ID: 829680cbe2f0
Revises: e41f154beedd
Create Date: 2026-01-23 20:20:27.581084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829680cbe2f0'
down_revision = 'e41f154beedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
