"""initial schema

Revision ID: 9e31be8cde26
Revises: 
Create Date: 2026-01-25 15:37:07.563695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e31be8cde26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('macro_categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pending_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_accounts_token'), ['token'], unique=True)

    op.create_table('account_beneficiari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_table('account_donatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partita_iva', sa.String(length=11), nullable=True),
    sa.Column('nome_attivita', sa.String(length=150), nullable=True),
    sa.Column('indirizzo_sede', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    op.create_table('account_enti_erogatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_organizzazione', sa.String(length=150), nullable=False),
    sa.Column('indirizzo_sede', sa.String(length=200), nullable=True),
    sa.Column('tipologia_ente', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sotto_categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('macro_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['macro_categoria_id'], ['macro_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donazioni_monetarie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donatore_id', sa.Integer(), nullable=False),
    sa.Column('ente_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donatore_id'], ['account_donatori.id'], ),
    sa.ForeignKeyConstraint(['ente_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punti_distribuzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('regione', sa.String(length=100), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=True),
    sa.Column('latitudine', sa.Float(), nullable=False),
    sa.Column('longitudine', sa.Float(), nullable=False),
    sa.Column('ente_erogatore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ente_erogatore_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('punto_distribuzione_id', sa.Integer(), nullable=False),
    sa.Column('sottocategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_distribuzione_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sotto_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recensione', sa.Text(), nullable=True),
    sa.Column('valutazione', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['account_beneficiari.id'], ),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni_alimentari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergeni', sa.String(length=255), nullable=True),
    sa.Column('scadenza', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni_igiene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatari', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni_medicinali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_medicinale', sa.String(length=100), nullable=True),
    sa.Column('scadenza', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni_mobilita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_mobilita', sa.String(length=100), nullable=True),
    sa.Column('stato', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni_vestiario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taglia', sa.String(length=20), nullable=True),
    sa.Column('condizioni', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donazioni_beni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donatore_id', sa.Integer(), nullable=False),
    sa.Column('ente_erogatore_id', sa.Integer(), nullable=False),
    sa.Column('bene_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bene_id'], ['beni.id'], ),
    sa.ForeignKeyConstraint(['donatore_id'], ['account_donatori.id'], ),
    sa.ForeignKeyConstraint(['ente_erogatore_id'], ['account_enti_erogatori.id'], ),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prenotazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('bene_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('data_prenotazione', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('codice_qr', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bene_id'], ['beni.id'], ),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['account_beneficiari.id'], ),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_qr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prenotazioni')
    op.drop_table('donazioni_beni')
    op.drop_table('beni_vestiario')
    op.drop_table('beni_mobilita')
    op.drop_table('beni_medicinali')
    op.drop_table('beni_igiene')
    op.drop_table('beni_alimentari')
    op.drop_table('feedback')
    op.drop_table('beni')
    op.drop_table('punti_distribuzione')
    op.drop_table('donazioni_monetarie')
    op.drop_table('sotto_categorie')
    op.drop_table('account_enti_erogatori')
    op.drop_table('account_donatori')
    op.drop_table('account_beneficiari')
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_accounts_token'))

    op.drop_table('pending_accounts')
    op.drop_table('macro_categorie')
    op.drop_table('accounts')
    # ### end Alembic commands ###
