"""Aggiunti orari e giorni ai punti distribuzione e dati all'Account Beneficiario

Revision ID: accd59667894
Revises: afb3a4268a2f
Create Date: 2026-01-26 14:59:39.717260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accd59667894'
down_revision = 'afb3a4268a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_beneficiari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascita', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('allergeni', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patologie', sa.Text(), nullable=True))
        batch_op.drop_column('codice_fiscale')

    with op.batch_alter_table('punti_distribuzione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giorni_apertura', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('orario_apertura', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('orario_chiusura', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('accettato', sa.Boolean(), nullable=False))
        batch_op.drop_column('citta')
        batch_op.drop_column('regione')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punti_distribuzione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regione', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('citta', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('accettato')
        batch_op.drop_column('orario_chiusura')
        batch_op.drop_column('orario_apertura')
        batch_op.drop_column('giorni_apertura')

    with op.batch_alter_table('account_beneficiari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codice_fiscale', sa.VARCHAR(length=16), nullable=False))
        batch_op.drop_column('patologie')
        batch_op.drop_column('allergeni')
        batch_op.drop_column('data_nascita')

    # ### end Alembic commands ###
