"""creazione

Revision ID: e41f154beedd
Revises: aa717192a570
Create Date: 2026-01-23 19:05:56.709372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41f154beedd'
down_revision = 'aa717192a570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_accounts_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_accounts_token'))

    op.drop_table('pending_accounts')
    # ### end Alembic commands ###
