"""migrazione segnalazioni e relazioni

Revision ID: 28f81ab4b72f
Revises: 43933f33248b
Create Date: 2026-01-23 11:20:25.776899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f81ab4b72f'
down_revision = '43933f33248b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segnalazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitudine', sa.Float(), nullable=False),
    sa.Column('longitudine', sa.Float(), nullable=False),
    sa.Column('tipo_bisogno', sa.Enum('ALIMENTI', 'MEDICINALI', 'ABBIGLIAMENTO', 'MOBILITA_E_SUPPORTO', 'CHILDREN', 'IGIENE', name='tipobisogno'), nullable=True),
    sa.Column('stato_approvazione', sa.Enum('IN_ATTESA', 'APPROVATA', 'RIFIUTATA', name='statoapprovazione'), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prenotazioni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'punti_distribuzione', ['punto_id'], ['id'])

    with op.batch_alter_table('sotto_categorie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('macro_categoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sotto_categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macro_categoria_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'macro_categorie', ['macro_categoria_id'], ['id'])

    with op.batch_alter_table('prenotazioni', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('punto_id')

    op.drop_table('segnalazioni')
    # ### end Alembic commands ###
