"""aggiornamento dei modelli

Revision ID: 43933f33248b
Revises: ec8f2e2756ab
Create Date: 2026-01-22 16:59:04.572259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43933f33248b'
down_revision = 'ec8f2e2756ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donazioni_monetarie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donatore_id', sa.Integer(), nullable=False),
    sa.Column('ente_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donatore_id'], ['account_enti_donatori.id'], ),
    sa.ForeignKeyConstraint(['ente_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('punto_distribuzione_id', sa.Integer(), nullable=False),
    sa.Column('sottocategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_distribuzione_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sotto_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prenotazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('bene_id', sa.Integer(), nullable=False),
    sa.Column('data_prenotazione', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('codice_qr', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bene_id'], ['beni.id'], ),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['account_beneficiari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_qr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prenotazioni')
    op.drop_table('beni')
    op.drop_table('donazioni_monetarie')
    # ### end Alembic commands ###
