"""Aggiunta classe Bene

Revision ID: 8ce76b34865b
Revises: 
Create Date: 2026-01-22 13:12:25.171726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce76b34865b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('macro_categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('account_beneficiari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_table('account_enti_donatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partita_iva', sa.String(length=11), nullable=False),
    sa.Column('nome_attivita', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    op.create_table('account_enti_erogatori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipologia_ente', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('indirizzo_sede', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sotto_categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('macro_categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['macro_categoria_id'], ['macro_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punti_distribuzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('indirizzo', sa.String(length=255), nullable=False),
    sa.Column('latitudine', sa.Float(), nullable=False),
    sa.Column('longitudine', sa.Float(), nullable=False),
    sa.Column('orari', sa.String(length=255), nullable=True),
    sa.Column('ente_erogatore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ente_erogatore_id'], ['account_enti_erogatori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('punto_distribuzione_id', sa.Integer(), nullable=False),
    sa.Column('sottocategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_distribuzione_id'], ['punti_distribuzione.id'], ),
    sa.ForeignKeyConstraint(['sottocategoria_id'], ['sotto_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beni')
    op.drop_table('punti_distribuzione')
    op.drop_table('sotto_categorie')
    op.drop_table('account_enti_erogatori')
    op.drop_table('account_enti_donatori')
    op.drop_table('account_beneficiari')
    op.drop_table('macro_categorie')
    op.drop_table('accounts')
    # ### end Alembic commands ###
