"""Aggiunta della classe Prenotazione

Revision ID: ecc710360ce2
Revises: 8ce76b34865b
Create Date: 2026-01-22 16:54:46.009052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc710360ce2'
down_revision = '8ce76b34865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prenotazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('bene_id', sa.Integer(), nullable=False),
    sa.Column('data_prenotazione', sa.DateTime(), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('codice_qr', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bene_id'], ['beni.id'], ),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['account_beneficiari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_qr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prenotazioni')
    # ### end Alembic commands ###
